{ __findFile, ... }: {
  den.hosts.x86_64-linux.igloo.users.lunixose = { };

  den.aspects.igloo = {
    includes = [
      <settings>
      <latitude3250>
      <disko-latitude3250>
      <lig/agenix>
    ];
    nixos =
      {
        config,
        pkgs,
        lib,
        modulesPath,
        ...
      }:
      {
        # Disk layout (fileSystems, boot.initrd.luks.devices, swapDevices) is
        # auto-generated by the `<disko-latitude3250>` aspect in
        # modules/disko/latitude3250.nix. Do not hand-write mounts here.
        boot.loader.systemd-boot.enable = true;
        boot.loader.efi.canTouchEfiVariables = true;
        boot.kernelPackages = pkgs.linuxPackages_latest;
        networking.hostName = "nixos";
      };
  };
}
