;;; lnav-config.el --- lnav bracket navigation (replaces smartparens)  -*- lexical-binding: t; -*-

(leaf lnav
  :ensure t
  :demand t
  :config
  ;; structural + TAB navigation everywhere
  ;; (global-lnav-mode 1)
  ;; lnav's C-c prefix collides with C-c d (deft) / C-c p (projectile);
  ;; its commands are bound under SPC o l in keybindings-config. Keep the
  ;; TAB/backtab chunk jumps.
  ;; pair highlight + auto-pair in every buffer; lnav-typing defers to
  ;; parinfer-rust in the lisp modes it owns (see lnav-typing--skip-p), so
  ;; enabling it globally matches smartparens' old auto-pair coverage while
  ;; parinfer keeps control of its modes.
  (add-hook 'after-change-major-mode-hook
            (lambda ()
              (lnav-show-pair-mode 1)
              (lnav-typing-mode 1)))
  ;; lnav-evil: text objects il/al + g* surround keys when evil is present
  ;; (its ###autoload isn't generated by the nix trivialBuild autoload pass)
  (after! evil
    (require 'lnav-evil)))
;;; lnav-config.el ends here
